#!/bin/bash
   
BASE_DIRECTORY=$(dirname "$(pwd)")

TOOL_DIRECTORY=$BASE_DIRECTORY/UMSD_v7.0.0/host/linux
PASSWD=ros
COMMAND=$1

shift

cd $TOOL_DIRECTORY
echo "$PASSWD" | sudo -S true

gnome-terminal -- bash -c "echo $PASSWD | sudo -S ./UMSD_MCLI -f umsd.cfg"
#MCLI_PID=$(echo $PASSWD | sudo -S lsof -i :5202 | grep "LISTEN" | awk '{print $2}')
echo "$@"
sleep 1
cd - > /dev/null

case $COMMAND in
   "setPhy")
      expect umsd_mcli setPhyMode "$@"
      ;;
   "setVlan")
      expect umsd_mcli dqacVlan bind "$@"
      ;;
   "resetVlan")
      expect umsd_mcli dqacVlan reset
      ;;
   *)
      echo -e "\n\nInvalid command: $COMMAND"
      echo "Usage: $0 {setPhy|setVlan|resetVlan} arg1 arg2 ..."
      sudo sh -c 'lsof -ti :5202 | xargs sudo kill -9'
      echo -e "\nPress Enter to continue..."
      read  
      exit 1
      ;;
esac
   #sudo kill $MCLI_PID

#TELNET_PID=$(echo $PASSWD | sudo -S lsof -i :5202 | grep "telnet" | awk '{print $2}') 
sleep 2
sudo lsof -ti :5202 | xargs sudo kill -9


exit 0
