#!/usr/bin/expect

set timeout 15
spawn telnet 127.0.0.1 8888
set args [lrange $argv 0 end]
expect "UMSD_MCLI>" {
    send "$args\r"
    expect "UMSD_MCLI>"
    sleep 1
    send "exit\r"
    expect eof }
exit
